$(document).ready(function(){
    $('.owl-carousel').owlCarousel({
    loop:false,
    margin:2,
    responsiveClass:true,
    responsive:{
        0:{
            items:4,
            nav:true
        },
        600:{
            items:3,
            nav:false
        },
        1000:{
            items:5,
            nav:true,
            loop:false
        }
    }
})

$("#hamburgerIcon").click(function(){
	$(".searchPad").slideToggle();
});
});
